# Generated by Django 2.2.1 on 2019-07-13 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('bestiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Bestiary')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('value', models.TextField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('ancestral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creature', to='sheets.Creature')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Chapter')),
                ('rule_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule_system.RuleSystem')),
                ('shared_with', models.ManyToManyField(related_name='sheets_creature_sharing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriety', to=settings.AUTH_USER_MODEL)),
                ('rule_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule_system.RuleSystem')),
                ('shared_with', models.ManyToManyField(related_name='sheets_character_sharing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
