# Generated by Django 2.2.1 on 2019-07-14 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='character',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='page',
            name='chapter',
        ),
        migrations.AddField(
            model_name='character',
            name='users_that_edit',
            field=models.ManyToManyField(related_name='sheets_character_edit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='users_that_see',
            field=models.ManyToManyField(related_name='sheets_character_see', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creature',
            name='users_that_edit',
            field=models.ManyToManyField(related_name='sheets_creature_edit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creature',
            name='users_that_see',
            field=models.ManyToManyField(related_name='sheets_creature_see', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='position',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='page',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='column',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='row',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ancestral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creature', to='sheets.Creature'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='field',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
