# Generated by Django 2.2.1 on 2019-08-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20190814_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_charisma_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_charisma_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_constitution_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_constitution_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_dexterity_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_dexterity_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_intelligence_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_intelligence_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_strength_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_strength_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_wisdom_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ability_wisdom_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='ancestral',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creature', to='sheets.Sheet_DnD35'),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='annotations_appearance',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='annotations_background',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='annotations_others',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_attacks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_base_attack_bonus',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_ca_flat_footed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_ca_natural_armor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_ca_other_modifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_ca_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_ca_touch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_damage_reduction',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_equipments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_grapple_others',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_grapple_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_hp_current',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_hp_nonlethal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_hp_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_initiative_others',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_initiative_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_special_attacks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_speed',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='battle_spell_resistance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Chapter'),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='companion_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='sheets.Sheet_DnD35'),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='companion_pet_master',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='sheets.Sheet_DnD35'),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_possessions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_riches',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_supplies',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_weight_heavy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_weight_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_weight_maximum',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_weight_medium',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='inventory_weight_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='magic_arcane_spell_failure',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='magic_slots',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='magic_spell_save',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='magic_spells',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='rule_system',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule_system.RuleSystem'),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_fortitude_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_fortitude_others',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_fortitude_temporary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_fortitude_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_reflex_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_reflex_others',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_reflex_temporary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_reflex_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_will_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_will_others',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_will_temporary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='saving_throws_will_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='talents_feats',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='talents_skills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_dnd35',
            name='talents_special_abilities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
