# Generated by Django 2.2.1 on 2019-08-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20190816_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet_dnd35',
            old_name='inventory_weight_total',
            new_name='inventory_weight_current',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='inventory_riches',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='inventory_supplies',
        ),
    ]
