# Generated by Django 2.2.1 on 2019-08-26 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0008_auto_20190817_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('rule_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule_system.RuleSystem')),
                ('users_that_edit', models.ManyToManyField(related_name='sheets_customcharacter_edit', to=settings.AUTH_USER_MODEL)),
                ('users_that_see', models.ManyToManyField(related_name='sheets_customcharacter_see', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomCreature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('ancestral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creature', to='sheets.CustomCreature')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Chapter')),
                ('rule_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule_system.RuleSystem')),
                ('users_that_edit', models.ManyToManyField(related_name='sheets_customcreature_edit', to=settings.AUTH_USER_MODEL)),
                ('users_that_see', models.ManyToManyField(related_name='sheets_customcreature_see', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('sheet_type', models.CharField(choices=[('CHA', 'Character'), ('CRB', 'Creature Base'), ('CRI', 'Creature Instance')], max_length=3)),
                ('ancestral', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creature', to='sheets.Sheet')),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Chapter')),
                ('rule_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule_system.RuleSystem')),
                ('users_that_edit', models.ManyToManyField(related_name='sheets_sheet_edit', to=settings.AUTH_USER_MODEL)),
                ('users_that_see', models.ManyToManyField(related_name='sheets_sheet_see', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='creature',
            name='ancestral',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='rule_system',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='users_that_edit',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='users_that_see',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='ancestral',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='companion_leader',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='companion_pet_master',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='rule_system',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='users_that_edit',
        ),
        migrations.RemoveField(
            model_name='sheet_dnd35',
            name='users_that_see',
        ),
        migrations.CreateModel(
            name='SheetDnD35',
            fields=[
                ('sheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sheets.Sheet')),
                ('information_name', models.TextField(blank=True, null=True)),
                ('information_classes', models.TextField(blank=True, null=True)),
                ('information_level', models.IntegerField(blank=True, default=None, null=True)),
                ('information_experience', models.IntegerField(blank=True, default=None, null=True)),
                ('information_race', models.TextField(blank=True, null=True)),
                ('information_gender', models.TextField(blank=True, null=True)),
                ('information_size', models.TextField(blank=True, null=True)),
                ('information_size_modifier_ca_and_attack', models.IntegerField(blank=True, default=None, null=True)),
                ('information_size_modifier_special_attacks', models.IntegerField(blank=True, default=None, null=True)),
                ('information_size_modifier_hide', models.IntegerField(blank=True, default=None, null=True)),
                ('information_age', models.TextField(blank=True, null=True)),
                ('information_alignment', models.TextField(blank=True, null=True)),
                ('information_deity', models.TextField(blank=True, null=True)),
                ('information_languages', models.TextField(blank=True, null=True)),
                ('ability_strength_base', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_strength_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_dexterity_base', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_dexterity_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_constitution_base', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_constitution_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_intelligence_base', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_intelligence_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_wisdom_base', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_wisdom_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_charisma_base', models.IntegerField(blank=True, default=None, null=True)),
                ('ability_charisma_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_fortitude_total', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_fortitude_base', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_fortitude_temporary', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_fortitude_others', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_reflex_total', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_reflex_base', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_reflex_temporary', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_reflex_others', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_will_total', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_will_base', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_will_temporary', models.IntegerField(blank=True, default=None, null=True)),
                ('saving_throws_will_others', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_speed', models.TextField(blank=True, default=None, null=True)),
                ('battle_initiative_total', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_initiative_others', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_hp_total', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_hp_current', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_hp_nonlethal', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_total', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_touch', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_flat_footed', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_equipment_armor', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_natural_armor', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_deflection_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_ca_other_modifier', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_damage_reduction', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_spell_resistance', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_base_attack_bonus', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_grapple_total', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_grapple_others', models.IntegerField(blank=True, default=None, null=True)),
                ('battle_attacks', models.TextField(blank=True, default=None, null=True)),
                ('battle_special_attacks', models.TextField(blank=True, default=None, null=True)),
                ('inventory_equipments', models.TextField(blank=True, default=None, null=True)),
                ('inventory_possessions', models.TextField(blank=True, default=None, null=True)),
                ('inventory_money', models.TextField(blank=True, default=None, null=True)),
                ('inventory_weight_current', models.IntegerField(blank=True, default=None, null=True)),
                ('inventory_weight_light', models.IntegerField(blank=True, default=None, null=True)),
                ('inventory_weight_medium', models.IntegerField(blank=True, default=None, null=True)),
                ('inventory_weight_heavy', models.IntegerField(blank=True, default=None, null=True)),
                ('inventory_weight_maximum', models.IntegerField(blank=True, default=None, null=True)),
                ('talents_skills', models.TextField(blank=True, default=None, null=True)),
                ('talents_feats', models.TextField(blank=True, default=None, null=True)),
                ('talents_special_abilities', models.TextField(blank=True, default=None, null=True)),
                ('magic_spells', models.TextField(blank=True, default=None, null=True)),
                ('magic_slots', models.TextField(blank=True, default=None, null=True)),
                ('magic_spell_save', models.IntegerField(blank=True, default=None, null=True)),
                ('magic_arcane_spell_failure', models.IntegerField(blank=True, default=None, null=True)),
                ('annotations_appearance', models.TextField(blank=True, default=None, null=True)),
                ('annotations_background', models.TextField(blank=True, default=None, null=True)),
                ('annotations_others', models.TextField(blank=True, default=None, null=True)),
                ('companion_leader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='sheets.SheetDnD35')),
                ('companion_pet_master', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='sheets.SheetDnD35')),
            ],
            options={
                'abstract': False,
            },
            bases=('sheets.sheet',),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Creature',
        ),
        migrations.DeleteModel(
            name='Sheet_DnD35',
        ),
    ]
