# Generated by Django 2.2.1 on 2019-08-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_auto_20190826_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcreature',
            name='ancestral',
        ),
        migrations.RemoveField(
            model_name='customcreature',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='customcreature',
            name='rule_system',
        ),
        migrations.RemoveField(
            model_name='customcreature',
            name='users_that_edit',
        ),
        migrations.RemoveField(
            model_name='customcreature',
            name='users_that_see',
        ),
        migrations.RemoveField(
            model_name='field',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='field',
            name='object_id',
        ),
        migrations.AddField(
            model_name='field',
            name='sheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
        migrations.DeleteModel(
            name='CustomCharacter',
        ),
        migrations.DeleteModel(
            name='CustomCreature',
        ),
    ]
