# Generated by Django 2.2.1 on 2019-09-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_auto_20190826_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetdnd35',
            name='bigStringInventory',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
