# Generated by Django 2.2.1 on 2019-09-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_sheetdnd35_bigstringinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetdnd35',
            old_name='bigStringInventory',
            new_name='bigStringAttacks',
        ),
        migrations.AddField(
            model_name='sheetdnd35',
            name='bigStringInventoryArmor',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sheetdnd35',
            name='bigStringInventoryOthers',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sheetdnd35',
            name='bigStringInventoryShield',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sheetdnd35',
            name='bigStringSkills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sheetdnd35',
            name='stringClass',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
