# Generated by Django 2.2.1 on 2019-09-26 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_auto_20190926_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='users_that_edit',
            field=models.ManyToManyField(blank=True, related_name='sheets_sheet_edit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='users_that_see',
            field=models.ManyToManyField(blank=True, related_name='sheets_sheet_see', to=settings.AUTH_USER_MODEL),
        ),
    ]
