# Generated by Django 2.2.1 on 2019-05-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencePointsReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_level', models.TextField()),
                ('difficulty_level', models.TextField()),
                ('experience_received', models.TextField()),
                ('rule_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.RuleSystem')),
            ],
        ),
    ]
