# Generated by Django 2.2.1 on 2019-05-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepointsreceived',
            name='character_level',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='experiencepointsreceived',
            name='difficulty_level',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='experiencepointsreceived',
            name='experience_received',
            field=models.CharField(max_length=50),
        ),
    ]
