# Generated by Django 2.2.1 on 2019-07-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20190529_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepointsreceived',
            name='rule_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_system.RuleSystem'),
        ),
        migrations.DeleteModel(
            name='RuleSystem',
        ),
    ]
