# Generated by Django 2.2.1 on 2019-07-12 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('shared_with', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
