# Generated by Django 2.2.1 on 2019-07-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shareable',
        ),
    ]
